# Generated by Django 3.2.4 on 2021-06-06 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='редагування (кількість аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='переклад (кількість аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='нормативних документів, наданих МОН України для публічного обговорення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_three',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='конкурсних робіт МАН'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='конкурсних дипломних проектів і робіт'),
        ),
    ]
