# Generated by Django 3.2.4 on 2021-06-06 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0003_auto_20210606_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_five',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(\\d+)\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='підручник за кордоном'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_four',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(\\d+)\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='навчальний посібник в Україні'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(\\d+)\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='курс лекцій'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_six',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(\\d+)\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='навчальний посібник за кордоном'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_three',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(\\d+)\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='підручник в Україні'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(\\d+)\\s*]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='видання методичних матеріалів навчально-методичні рекомендації'),
        ),
    ]
