# Generated by Django 3.2.4 on 2021-06-28 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0004_auto_20210606_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericreportdata',
            options={'verbose_name': 'Загальний звіт', 'verbose_name_plural': 'Загальні звіти'},
        ),
        migrations.AddField(
            model_name='genericreportdata',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Чи закрито звітний період'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eight_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='І освітній рівень'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eight_three',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='ІІІ освітній рівень'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eight_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='ІІ освітній рівень'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eleven_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка і підготовка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eleven_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fifteen_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fifteen_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='редагування (кількість аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='переклад (кількість аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='four_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='кількість виконавців одного документу'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fourteen_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='підготовка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fourteen_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nine_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nine_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='one_four',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='середньорічне навчальне навантаження в ДНУ (год.)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='one_one',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='обсяг виконаного аудиторного навантаження (год.)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='one_three',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='загальне навчальне навантаження працівника (год.) за рік'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='one_two',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='обсяг виконаного аудиторного навантаження (год.) іноземною мовою'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_five',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(,.)\\d+(;|$)\\s+]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='підручник за кордоном'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_four',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(,.)\\d+(;|$)\\s+]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='навчальний посібник в Україні'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(,.)\\d+(;|$)\\s+]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='курс лекцій'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_six',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(,.)\\d+(;|$)\\s+]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='навчальний посібник за кордоном'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_three',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(,.)\\d+(;|$)\\s+]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='підручник в Україні'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(,.)\\d+(;|$)\\s+]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='видання методичних матеріалів навчально-методичні рекомендації'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seventeen_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка і впровадження'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_one',
            field=models.IntegerField(default='0', validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='керівнику (на всіх виконавців)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_five',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_four',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_six',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_three',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_four',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='робочих навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_three',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='робочих навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='thirteen_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='ліцензійної'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='thirteen_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='акредитаційної'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='twelve_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='розробка та затвердження'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='методичних вказівок (рекомендацій)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_three',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='навчально-методичних матеріалів (підручників, посібників тощо), що подаються МОН України на закрите рецензування'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='навчально-методичних посібників, посібників'),
        ),
        migrations.AlterField(
            model_name='genericreportdata',
            name='assignment_duration',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Кількість відпрацьованих місяців за звітний період'),
        ),
        migrations.AlterField(
            model_name='genericreportdata',
            name='main_assignment',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Відсоток ставки, яку обіймає за основною посадою'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='eight_one',
            field=models.IntegerField(default=0, verbose_name='кількість перевірених робіт'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='seven_one',
            field=models.IntegerField(default=0, verbose_name='кількість відпрацьованих днів'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='ten_one',
            field=models.IntegerField(default=0, verbose_name='кількість студентів, яким замовлено'),
        ),
        migrations.AddConstraint(
            model_name='reportperiod',
            constraint=models.UniqueConstraint(fields=('report_period',), name='unique_report_period_report_period'),
        ),
    ]
