# Generated by Django 3.2.4 on 2021-06-29 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0005_auto_20210628_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_one',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='редагування (кількість друкованих аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('\\d+([,.]\\d+)?', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='переклад (кількість друкованих аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_two',
            field=models.CharField(default='0', max_length=256, validators=[django.core.validators.RegexValidator('^[\\d+(,.)\\d+(;|$)\\s+]+$', message='Невірний формат даних. Введіть числа через пробіл.')], verbose_name='навчально-методичні рекомендації'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_one',
            field=models.IntegerField(default='0', validators=[django.core.validators.RegexValidator('\\d+?(;|$)', message='Невірний формат даних. Введіть числа через крапку з комою.')], verbose_name='кількість виконавців проєкту'),
        ),
    ]
