# Generated by Django 3.2.4 on 2021-07-02 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0006_auto_20210629_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Додано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Останнє редагування'),
        ),
        migrations.AddField(
            model_name='genericreportdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Додано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericreportdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Останнє редагування'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Додано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Останнє редагування'),
        ),
        migrations.AddField(
            model_name='scientificandinnovativework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Додано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificandinnovativework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Останнє редагування'),
        ),
    ]
