# Generated by Django 3.2.4 on 2021-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0008_auto_20210712_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='thirteen_three',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='thirteen_two',
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='fifteen_one',
            field=models.IntegerField(default=0, verbose_name='кількість відвіданих занять'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='four_five',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота в раді та бюро із забезпечення якості вищої освіти (РЗЯВО, БЗЯВО)'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='four_four',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота в раді та бюро із забезпечення якості вищої освіти (РЗЯВО, БЗЯВО)'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='four_one',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота в науково-технічній раді НДЧ ДНУ'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='four_six',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота у бюро з академічної доброчесності факультету'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='four_three',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота в науково-методичній раді'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='four_two',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота в науково-методичній раді'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='one_one',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='посада'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='thirteen_one',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота у складі вченої ради факультету'),
        ),
    ]
