# Generated by Django 3.2.4 on 2021-08-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0010_reportperiod_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportperiod',
            name='document',
            field=models.FileField(default=None, max_length=256, null=True, upload_to='uploads/service_api/report_period', verbose_name='Положення'),
        ),
    ]
