# Generated by Django 3.2.4 on 2021-09-03 18:41

from django.db import migrations, models
import service_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0011_alter_reportperiod_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eleven_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка і підготовка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eleven_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fifteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fifteen_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='редагування (кількість друкованих аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='переклад (кількість друкованих аркушів)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='four_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='кількість виконавців одного документу'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fourteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='підготовка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fourteen_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nine_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nine_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_five',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='підручник за кордоном'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='навчальний посібник в Україні'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='курс лекцій'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_six',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='навчальний посібник за кордоном'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='підручник в Україні'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='навчально-методичні рекомендації'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seventeen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка і впровадження'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_five',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_six',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='робочих навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='робочих навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='thirteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='ліцензійної'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='thirteen_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='акредитаційної'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='twelve_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка та затвердження'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='методичних вказівок (рекомендацій)'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='навчально-методичних матеріалів (підручників, посібників тощо), що подаються МОН України на закрите рецензування'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='навчально-методичних посібників, посібників'),
        ),
    ]
