# Generated by Django 3.2.4 on 2021-09-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
        ('service_api', '0012_auto_20210903_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportperiod',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_app.documents'),
        ),
    ]
