# Generated by Django 3.2.4 on 2021-09-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0013_alter_reportperiod_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='generic_report_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_api.genericreportdata'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='generic_report_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_api.genericreportdata'),
        ),
        migrations.AlterField(
            model_name='scientificandinnovativework',
            name='generic_report_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_api.genericreportdata'),
        ),
    ]
