# Generated by Django 3.2.4 on 2021-10-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0015_alter_genericreportdata_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Місце за рейтингом'),
        ),
        migrations.AddField(
            model_name='genericreportdata',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Місце за рейтингом'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Місце за рейтингом'),
        ),
        migrations.AddField(
            model_name='scientificandinnovativework',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Місце за рейтингом'),
        ),
    ]
