# Generated by Django 3.2.4 on 2022-06-05 19:29

import django.core.validators
from django.db import migrations, models
import service_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0015_alter_genericreportdata_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='seven_five',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='seven_four',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='seven_six',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='seven_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='sixteen_five',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='sixteen_four',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='sixteen_six',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='sixteen_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='ten_four',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='ten_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='thirteen_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='two_three',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='fourteen_two',
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='eight_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='eighteen_two',
            field=models.IntegerField(default=0, verbose_name='Кількість виконвавців проєкту'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fifteen_five',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fifteen_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fifteen_six',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fifteen_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='nineteen_three',
            field=models.IntegerField(default=0, verbose_name='регіонального рівня'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='nineteen_two',
            field=models.IntegerField(default=0, verbose_name='всеукраїнського рівня'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seventeen_three',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='конкурсних робіт МАН'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seventeen_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='конкурсних дипломних проєктів і робіт'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='six_five',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='підручник за кордоном офіційною мовою ЄС'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='six_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='навчальний посібник в Україні'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='six_six',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='навчальний посібник за кордоном офіційною мовою ЄС'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='six_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='підручник в Україні'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='three_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='робочих навчальних планів'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twelve_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_one',
            field=models.IntegerField(default=0, verbose_name='міжнародного рівня'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_one_one',
            field=models.IntegerField(default=0, verbose_name='олімпіади, чемпіонату світу'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_one_three',
            field=models.IntegerField(default=0, verbose_name='чемпіонату України'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_one_two',
            field=models.IntegerField(default=0, verbose_name='чемпіонату Європи'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_three',
            field=models.IntegerField(default=0, verbose_name='регіонального рівня'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_three_one',
            field=models.CharField(blank=True, choices=[(None, 'Не отримано'), ('honored_worker_of_education_of_ukraine', 'Заслужений працівник освіти України'), ('excellent_education', 'Відмінник освіти'), ('honored_professor_lecturer_of_dnu', 'Заслужений професор(викладач) ДНУ'), ('honored_lecturer_of_dnu', 'Заслужений викладач ДНУ'), ('professor', 'Професор'), ('docent', 'Доцент')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_two',
            field=models.IntegerField(default=0, verbose_name='всеукраїнського рівня'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_two_one',
            field=models.IntegerField(default=0, verbose_name='олімпіади, чемпіонату світу'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='twenty_two_two',
            field=models.IntegerField(default=0, verbose_name='чемпіонату Європи'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='fifteen_two',
            field=models.BooleanField(default=False, verbose_name='заступник завідувача кафедри на громадських засадах'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_five_one',
            field=models.BooleanField(default=False, verbose_name='ДНУ'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_four_one',
            field=models.IntegerField(default=0, verbose_name='кількість видів робіт'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_seven_one',
            field=models.BooleanField(default=False, verbose_name='міжнародних'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_seven_three',
            field=models.BooleanField(default=False, verbose_name='обласних'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_seven_two',
            field=models.BooleanField(default=False, verbose_name='національних'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_six_one',
            field=models.BooleanField(default=False, verbose_name='України'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_six_two',
            field=models.BooleanField(default=False, verbose_name='області'),
        ),
        migrations.AddField(
            model_name='organizationalandeducationalwork',
            name='twenty_three_one',
            field=models.IntegerField(default=0, verbose_name='Кількість виконавців одного документу'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eight_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eighteen_one',
            field=models.BooleanField(default=False, verbose_name='Керівник'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eleven_one',
            field=models.IntegerField(default=0, verbose_name='розробка і підготовка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eleven_two',
            field=models.IntegerField(default=0, verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='ліцензійної'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='акредитаційної'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='four_one',
            field=models.CharField(blank=True, choices=[(None, '-'), ('І освітній рівень', 'І освітній рівень'), ('ІІ освітній рівень', 'ІІ освітній рівень'), ('ІІІ освітній рівень', 'ІІІ освітній рівень')], default=None, max_length=32, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fourteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nine_one',
            field=models.IntegerField(default=0, verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nine_two',
            field=models.IntegerField(default=0, verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nineteen_one',
            field=models.IntegerField(default=0, verbose_name='міжнародного рівня'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='редагування'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='переклад'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seventeen_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='нормативних документів, наданих МОН України для публічного обговорення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='курс лекцій'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='навчально-методичні рекомендації'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='навчально-методичних посібників, посібників'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='sixteen_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='навчально-методичних матеріалів (підручників, посібників тощо), що подаються МОН України на закрите рецензування'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка і підготовка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='thirteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка і впровадження'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.number_semicolon_validator], verbose_name='робочих навчальних планів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='twelve_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='підготовка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='розробка та затвердження'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='eleven_one',
            field=models.IntegerField(default=0, verbose_name='Виконання обов’язків куратора (наставника) академічної групи'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='fifteen_one',
            field=models.BooleanField(default=False, verbose_name='завідувача кафедри (у тому числі відвідування занять завідувачем кафедри зі складанням відгуку, проведення засідань кафедри, участь у засіданнях  деканату факультету)'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='fourteen_one',
            field=models.IntegerField(default=0, verbose_name='Кількість захищених робіт'),
        ),
    ]
