# Generated by Django 3.2.16 on 2024-05-08 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import service_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210628_1834'),
        ('service_api', '0016_auto_20220605_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='eighteen_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='eighteen_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='eleven_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='fifteen_five',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='fifteen_four',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='fifteen_six',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='fifteen_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='fifteen_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='nine_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='nineteen_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='nineteen_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='nineteen_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='seventeen_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='seventeen_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='seventeen_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='six_five',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='six_six',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='sixteen_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='sixteen_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='three_four',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='three_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twelve_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_one_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_one_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_one_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_three',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_three_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_two',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_two_one',
        ),
        migrations.RemoveField(
            model_name='educationalandmethodicalwork',
            name='twenty_two_two',
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='five_four',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='виконавець'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='five_three',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='відповідальна особа'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fourteen_five',
            field=models.IntegerField(default=0, verbose_name='персональна участь'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fourteen_four',
            field=models.IntegerField(default=0, verbose_name='підготовка та участь студента чи групи студентів'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fourteen_six',
            field=models.IntegerField(default=0, verbose_name='підготовка та участь студента чи групи студентів'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='fourteen_three',
            field=models.IntegerField(default=0, verbose_name='персональна участь'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seven_eight',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='повторне видання'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seven_five',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='публікація'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seven_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='повторне видання'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seven_seven',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='публікація'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seven_six',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='повторне видання'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='seven_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='публікація'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='ten_three',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='на другий ОР'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='thirteen_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='учасник'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='two_four',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='розробник'),
        ),
        migrations.AddField(
            model_name='educationalandmethodicalwork',
            name='two_three',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='гарант'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eight_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eight_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='eleven_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='рецензування'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fifteen_one',
            field=models.CharField(blank=True, choices=[(None, 'Не отримано'), ('honored_worker_of_education_of_ukraine', 'Заслужений працівник освіти України'), ('excellent_education', 'Відмінник освіти'), ('honored_professor_lecturer_of_dnu', 'Заслужений професор(викладач) ДНУ'), ('honored_lecturer_of_dnu', 'Заслужений викладач ДНУ'), ('professor', 'Професор'), ('docent', 'Доцент')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='відповідальна особа'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='five_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='виконавець'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fourteen_one',
            field=models.IntegerField(default=0, verbose_name='персональна участь'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='fourteen_two',
            field=models.IntegerField(default=0, verbose_name='підготовка та участь студента чи групи студентів'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='nine_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='запровадження'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='публікація'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='seven_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='повторне видання'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_four',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='повторне видання'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='публікація'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_three',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='публікація'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='six_two',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_brackets_float_number_semicolon_validator], verbose_name='повторне видання'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='на перший ОР зі скороченим терміном навчання'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='ten_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='на перший ОР на базі ПЗСО'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='thirteen_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='керівник'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='розробка'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='three_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='оновлення'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='twelve_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='експертиза'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='гарант'),
        ),
        migrations.AlterField(
            model_name='educationalandmethodicalwork',
            name='two_two',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='розробник'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='twenty_three_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='Кількість виконавців одного документу'),
        ),
    ]
