# Generated by Django 3.2.16 on 2024-05-09 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import service_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210628_1834'),
        ('service_api', '0017_auto_20240508_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='seventeen_eight',
            new_name='thirteen_eight',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='seventeen_five',
            new_name='thirteen_five',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='seventeen_four',
            new_name='thirteen_four',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='seventeen_seven',
            new_name='thirteen_seven',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='seventeen_six',
            new_name='thirteen_six',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='seventeen_three',
            new_name='thirteen_three',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='seventeen_two',
            new_name='thirteen_two',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='twenty_seven_three',
            new_name='twenty_one_three',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='twenty_seven_two',
            new_name='twenty_one_two',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='twenty_five_one',
            new_name='twenty_zero_three',
        ),
        migrations.RenameField(
            model_name='organizationalandeducationalwork',
            old_name='twenty_six_two',
            new_name='twenty_zero_two',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='fifteen_two',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='five_three',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='six_two',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='twenty_four_one',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='twenty_seven_one',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='twenty_six_one',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='twenty_three_one',
        ),
        migrations.RemoveField(
            model_name='organizationalandeducationalwork',
            name='twenty_two_one',
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='eight_one',
            field=models.IntegerField(default=0, verbose_name='Виконання обов’язків куратора (наставника) академічної групи'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='eighteen_one',
            field=models.CharField(default='0', max_length=256, validators=[service_api.models.float_number_semicolon_validator], verbose_name='Кількість виконавців одного документу'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='eleven_one',
            field=models.BooleanField(default=False, verbose_name='завідувача кафедри (у тому числі відвідування занять завідувачем кафедри зі складанням відгуку, проведення засідань кафедри, участь у засіданнях  деканату факультету)'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='eleven_two',
            field=models.BooleanField(default=False, verbose_name='заступник завідувача кафедри на громадських засадах'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='fifteen_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='five_one',
            field=models.BooleanField(default=False, verbose_name='навчальна робота'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='five_two',
            field=models.BooleanField(default=False, verbose_name='інші види діяльності'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='fourteen_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='nine_one',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота у складі вченої ради факультету'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='nineteen_one',
            field=models.IntegerField(default=0, verbose_name='кількість видів робіт'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='seven_one',
            field=models.IntegerField(default=0, verbose_name='кількість студентів, яким замовлено додатки'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='seventeen_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='six_one',
            field=models.IntegerField(default=0, verbose_name='кількість відпрацьованих днів'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='sixteen_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='ten_one',
            field=models.CharField(blank=True, choices=[(None, '-'), ('head', 'голова, заступник голови'), ('secretary', 'секретар'), ('member', 'член')], default=None, max_length=10, null=True, verbose_name='Робота у складі вченої ради факультету'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='thirteen_one',
            field=models.BooleanField(default=False, verbose_name='відповідальний секретар'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='twelve_one',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='участь у профорієнтаційній роботі'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='twenty_one_one',
            field=models.BooleanField(default=False, verbose_name='міжнародних'),
        ),
        migrations.AlterField(
            model_name='organizationalandeducationalwork',
            name='twenty_zero_one',
            field=models.BooleanField(default=False, verbose_name='України'),
        ),
    ]
