# Generated by Django 3.2.16 on 2025-06-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210628_1834'),
        ('service_api', '0018_auto_20240509_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationalandmethodicalwork_place', models.IntegerField(blank=True, null=True)),
                ('organizationalandeducationalwork_place', models.IntegerField(blank=True, null=True)),
                ('scientificandinnovativework_place', models.IntegerField(blank=True, null=True)),
                ('scores_sum', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('generic_report_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_api.genericreportdata')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsOfDepartmentsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to_department_sum', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('related_to_department_count', models.IntegerField(blank=True, null=True)),
                ('scores_sum', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('teacher_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_api.teacherresults')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_sum', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('places_sum_count', models.IntegerField(blank=True, null=True)),
                ('places_sum_average', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.faculty')),
                ('report_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.reportperiod')),
            ],
        ),
        migrations.CreateModel(
            name='DecansResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_place', models.IntegerField(blank=True, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('teacher_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_api.teacherresults')),
            ],
        ),
    ]
