# Generated by Django 3.2.4 on 2021-06-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210606_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title'], 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедри'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['department__title', 'department__faculty__title'], 'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профілі користувачів'},
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.faculty', verbose_name='факультет'),
        ),
        migrations.AlterField(
            model_name='position',
            name='cumulative_calculation',
            field=models.CharField(blank=True, choices=[('department', 'По Кафедрі'), ('faculty', 'По Факультету')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.position'),
        ),
    ]
