# Generated by Django 3.2.4 on 2021-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedMicrosoftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail', models.CharField(default='', help_text='To be checked literally with an income User email', max_length=256)),
            ],
        ),
    ]
