# Generated by Django 3.2.4 on 2021-07-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_microsoft_oauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedMicrosoftAccount',
        ),
    ]
