name: Deploy

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy DNU Academic Rating
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        key_path: ${{ secrets.KEY_PATH }}
        script: . /root/update.sh
